name: Make Docs
on: push

jobs:
  make_docs:
    runs-on: ubuntu-latest
    name: Build Docs and Presentations
    steps:
    - uses: actions/checkout@v2

    - run: sudo apt update && sudo apt upgrade && sudo apt install texlive-latex-recommended texlive-latex-extra texlive-pictures pandoc util-linux

    - run: cd docs && make

    - uses: actions/upload-artifact@v2
      with:
        name: Docs (.pdf)
        path: docs/_build/pdf/*.pdf
