name: Make Docs
on:
  push:
    paths:
      - 'docs/**'
  release:

jobs:
  make_docs:
    runs-on: ubuntu-latest
    name: Doc Builder
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - run: sudo apt install texlive-latex-recommended texlive-latex-extra texlive-pictures pandoc rename

    - run: cd docs && make

    - uses: actions/upload-artifact@v2
      with:
        name: Team_Gold_Docs
        path: docs/_build/pdf/*.pdf
