name: Make Arduino
on:
  push:
    paths:
      - 'arduino/**'
  pull_request:
  release:

jobs:
  make_bin:
    runs-on: ubuntu-latest
    name: Binary Builder
    steps:
    - uses: actions/checkout@v2

    - run: cd arduino/lab1 && make bin

    - uses: actions/upload-artifact@v2
      with:
        name: Team_Gold_Arduino_Binaries
        path: arduino/lab1/_build/arduino.avr.mega/*
  
  make_lint:
    runs-on: ubuntu-latest
    name: c++ Delinter
    steps:
    - uses: actions/checkout@v2

    - run: touch arduino/lab1/README.md
    - run: touch arduino/lab1/COPYING

    - run: cd arduino/lab1 && make lint
